### ISSUE TITLE
🐛 loquiAPI not working 

### ISSUE THREAD

**Issue by cansavvy** [FredHutch/loquiAPI#1]
## Background:

Was trying to use loquiAPI to make videos from google slides. I'm really excited about this API tool @howardbaek and so glad you could put it together. We are going to use it to put an automatic script together for the videos we generate for this course: https://github.com/fhdsl/AI_for_Decision_Makers

## Steps I took 

I installed loquiAPI using: 

```
devtools::install_github("FredHutch/loquiAPI")
```
Then I tried to run the main argument as described by the README: 
```
loquiAPI::generate_from_gs("https://docs.google.com/presentation/d/1Le4EqKaQKJskZDFrO0h2I0mP-s23C8UHFenhMeFpmu8/edit#slide=id.p")
```

I get this error when I try to run this: 

```
Error in loquiAPI::generate_from_gs("https://docs.google.com/presentation/d/1Le4EqKaQKJskZDFrO0h2I0mP-s23C8UHFenhMeFpmu8/edit#slide=id.p") : 
  Bad Gateway (HTTP 502).
```

### Things I tried 

- [x] These slides are shared and made viewable by the public. 
- [x] Tried using the example verbatim as described in the README https://github.com/FredHutch/loquiAPI?tab=readme-ov-file#example but that also gave the 502 error. 

Second related but maybe not related, I'm noticing in the SwaggerUI docs it shows all the parameters are required (are there not defaults for these?) If these docs are true, we should help users by putting in reasonable defaults so all they need to do is provide slides if they would like. 
<img width="614" alt="Screenshot 2024-01-02 at 11 29 17 AM" src="https://github.com/FredHutch/loquiAPI/assets/23458084/37504ecd-81ae-49fa-82e8-b7664e93c28f">

But if these docs are not accurate, we should fix the docs.

**Comment by howardbaek** [comment]
Were you able to run `loquiAPI::generate_from_gs("https://docs.google.com/presentation/d/1Le4EqKaQKJskZDFrO0h2I0mP-s23C8UHFenhMeFpmu8/edit#slide=id.p")`? This is the first of your two calls `generate_from_gs()` in the issue.

**Comment by cansavvy** [comment]
>loquiAPI::generate_from_gs("https://docs.google.com/presentation/d/1Le4EqKaQKJskZDFrO0h2I0mP-s23C8UHFenhMeFpmu8/edit#slide=id.p")

No. I get a 502 error when I run this.

**Comment by cansavvy** [comment]
The example in the readme also fails.

**Comment by howardbaek** [comment]
Parallelization is needed so multiple users can use this API and the queue doesn't get stuck with multiple requests to the API.

**Comment by howardbaek** [comment]
https://github.com/FredHutch/loquiAPI/pull/6 fixes this.
